### ISSUE TITLE
ERROR:  does not have a library for the current platform

### ISSUE THREAD

**Issue by carlosdp** [GodotVR/godot-oculus-mobile-asset#3]
With GLES2 enabled, I get these errors and a blank white screen when opening the project in the editor with this addon installed (Windows):

```
ERROR:  does not have a library for the current platform.
   At: modules/gdnative/nativescript/nativescript.cpp:1483
ERROR:  does not have a library for the current platform.
   At: modules/gdnative/nativescript/nativescript.cpp:1483
```

Weird thing is, with GLES3, the errors still appear, but the editor starts up fine. The workaround is to open `project.godot` and comment out the GDNative singletons, which allows the editor to open correctly. But if I close and re-open the project, the issue persists.

**Comment by NeoSpark314** [comment]
The error is ok and not an actual problem (it appears for me also and it never caused a problem). This happens because the library exists only for android. 
Your white screen problem is very likely unrelated to this error. How does your project look? Do you reference something from the godot oculus library from within the edtior (maybe a tool script?). Could you upload a small reproduer project maybe?

**Comment by carlosdp** [comment]
Yea you're right, there's something weird going on with GLES2 for me. I'm not using any tool scripts, but even if I get the editor to open, when I run the project, I get a white screen in the game viewport. It's a super bare bones project with just the basic VR stuff, very strange. But yea, probably not directly related to ovrmobile

**Comment by carlosdp** [comment]
Hmm, it looks like it's actually being caused by godot_oculus somehow (I have both because I'm supporting both)

**Comment by carlosdp** [comment]
Yea nevermind, it was the godot_oculus addon causing the issue, which I guess isn't strickly necessary at the moment since the basic VR stuff for oculus is built in to the engine now. I'll close this, thanks!

**Comment by NeoSpark314** [comment]
Ok; no problem; 
Maybe it's worth opening an issue in the godot_oculus git repo for this? GLES2 is essential for the quest; and I see that with Oculus Link now many more people might try to do cross platform dev...
